version: 0.3_build{build}

image: Visual Studio 2017
platform: x64
configuration: Release

clone_folder: c:\projects\mayo

matrix:
  fast_finish: true

install:
  - ps: Invoke-WebRequest -Uri http://www.fougue.pro/share/bin/OpenCASCADE-7.4.0-vc14-64.rar -OutFile .\OpenCASCADE-7.4.0-vc14-64.rar
  - 7z x OpenCASCADE-7.4.0-vc14-64.rar

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - call "OpenCASCADE-7.4.0-vc14-64\opencascade-7.4.0\env.bat"
  - set PATH=C:\Qt\5.13\msvc2017_64\bin;%PATH%
  - set PATH=C:\Qt\Tools\QtCreator\bin;%PATH%
  - qmake --version

build_script:
  - mkdir build
  - cd build
  - qmake ..\mayo.pro
  - jom -j%NUMBER_OF_PROCESSORS%
  - cd ..

test_script:
  - mkdir build-tests
  - cd build-tests
  - qmake ..\tests\mayo_tests.pro
  - jom -j%NUMBER_OF_PROCESSORS%
  - release\mayo_tests.exe

on_success:
  - ps: >-
      if ($true)
      {
          Write-Host "Success"
      }
