version: 0.3_build{build}

image: Visual Studio 2017
platform: x64
configuration: Release

clone_folder: c:\projects\mayo

matrix:
  fast_finish: true

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\VC\Auxiliary\Build\vcvars64.bat"
  - set PATH=C:\Qt\5.13\msvc2017_64\bin;%PATH%
  - ps: Invoke-WebRequest -Uri http://www.fougue.pro/share/bin/OpenCASCADE-7.4.0-vc14-64.rar -OutFile .\OpenCASCADE-7.4.0-vc14-64.rar
  - 7z x OpenCASCADE-7.4.0-vc14-64.rar

before_build:
  - qmake --version
  - echo NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%
  - call "OpenCASCADE-7.4.0-vc14-64\opencascade-7.4.0\env.bat"

build_script:
  - mkdir build
  - cd build
  - qmake ..\mayo.pro
  - nmake
  - cd ..

on_success:
- ps: >-
    if ($true)
    {
      Write-Host "Success"
    }
