version: 0.3_build{build}

image: Visual Studio 2017

platform:
  - x64

configuration:
#  - Debug
  - Release

clone_folder: c:\projects\mayo

install:
  - set PATH=C:\Qt\5.14.2\msvc2017_64\bin;%PATH%
  - ps: Invoke-WebRequest -Uri http://www.fougue.pro/share/bin/OpenCASCADE-7.4.0-vc14-64.zip -OutFile .\OpenCASCADE-7.4.0-vc14-64.zip
  - 7z e OpenCASCADE-7.4.0-vc14-64.zip

before_build:
  - echo NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%
  - call "OpenCASCADE-7.4.0-vc14-64\opencascade-7.4.0\env.bat"

build_script:
  - mkdir build
  - cd build
  - qmake ..\mayo.pro
  - nmake

on_success:
- ps: >-
    if ($true)
    {
      Write-Host "Success"
    }
